# Generated by Django 5.0.3 on 2024-04-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name', 'product_slug', '-product_created'], name='shop_app_pr_product_865229_idx'),
        ),
    ]
